# Numpy

In [1]:
import numpy as np

## Arrays (NDArrays)

In [2]:
payments_list = [6.99, 12.40, 75, 1.55]

In [3]:
payments = np.array(payments_list)

In [4]:
print(payments)

[ 6.99 12.4  75.    1.55]


In [5]:
payments

array([ 6.99, 12.4 , 75.  ,  1.55])

In [6]:
type(payments)

numpy.ndarray

In [7]:
img = np.array([[0, 1, 0, 1, 0],
                [0, 0, 1, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 1, 1, 1, 0]])

In [8]:
img

array([[0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0]])

In [10]:
payments.shape

(4,)

In [11]:
payments.size

4

In [12]:
payments.ndim

1

In [13]:
img.shape

(4, 5)

In [14]:
img.size

20

In [15]:
img.ndim

2

In [16]:
payments.dtype

dtype('float64')

In [17]:
img.dtype

dtype('int64')

In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
np.arange(0, 10_000, 500.1)

array([   0. ,  500.1, 1000.2, 1500.3, 2000.4, 2500.5, 3000.6, 3500.7,
       4000.8, 4500.9, 5001. , 5501.1, 6001.2, 6501.3, 7001.4, 7501.5,
       8001.6, 8501.7, 9001.8, 9501.9])

## Manipulation

In [22]:
payments * 2

array([ 13.98,  24.8 , 150.  ,   3.1 ])

In [23]:
payments - payments * 0.2

array([ 5.592,  9.92 , 60.   ,  1.24 ])

In [25]:
img > 0

array([[False,  True, False,  True, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True, False]])

In [33]:
(payments > 30) | (payments < 10)

array([ True, False,  True,  True])

In [27]:
(payments > 30).sum()

np.int64(1)

## Masking

In [29]:
payments

array([ 6.99, 12.4 , 75.  ,  1.55])

In [28]:
payments[payments > 30]

array([75.])

In [30]:
img[img>0]

array([1, 1, 1, 1, 1, 1])

In [34]:
payments[(payments > 30) | (payments < 10)]

array([ 6.99, 75.  ,  1.55])

### Slicing

In [35]:
payments[0]

np.float64(6.99)

In [36]:
payments[-1]

np.float64(1.55)

In [37]:
payments[0:3]

array([ 6.99, 12.4 , 75.  ])

In [38]:
payments[[0, 2]]

array([ 6.99, 75.  ])

In [41]:
img

array([[0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0]])

In [39]:
img[0]

array([0, 1, 0, 1, 0])

In [40]:
img[0, 0]

np.int64(0)

In [42]:
img[1, 2]

np.int64(1)

In [45]:
img[:, 2]

array([0, 1, 0, 1])